from typing import Any

class PubSub:
    conn: Any = ...
    def __init__(self, conn: Any) -> None: ...
    def subscribe(self, detailed_event: Any, handler: Any) -> None: ...
    def unsubscribe(self, handler: Any): ...
    def emit(self, event: Any, data: Any) -> None: ...
